alertmanager:
  enabled: false
  ingress:
    enabled: false
    ingressClassName: nginx
    hosts:
      - paths: "/"
    pathType: ImplementationSpecific
  alertmanagerSpec:
    replicas: 3
grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    path: "/"
prometheusOperator:
  enabled: true
prometheus:
  enabled: true
kubeApiServer:
  enabled: true
kubelet:
  enabled: true
kubeControllerManager:
  enabled: true
coreDns:
  enabled: true
kubeDns:
  enabled: true
kubeEtcd:
  enabled: true
kubeScheduler:
  enabled: true
kubeProxy:
  enabled: true
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
