apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: user@example.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - selector: {}
        dns01:
          route53:
            region: <region>
            accessKeyID: <access-key>
            secretAccessKeySecretRef:
              name: route53-secret
              key: secret-access-key
            role: <iam-role-arn>
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: user@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-key
    solvers:
      - selector: {}
        dns01:
          route53:
            region: <region>
            accessKeyID: <access-key>
            secretAccessKeySecretRef:
              name: route53-secret
              key: secret-access-key
            role: <iam-role-arn>
