name: Docker Image VKPR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.vertigo-devops.com/vkpr-teste:slim 
    - name: Login to Nexus
      uses: docker/login-action@v2
      with:
          registry: ${{ secrets.NEXUS_URL_KEY }}
          username: ${{ secrets.NEXUS_LOGIN_KEY }}
          password: ${{ secrets.NEXUS_PASSWORD_KEY }}
    - name: Docker Push
      run: docker push docker.vertigo-devops.com/vkpr-teste:slim  
          
