name: Docker Image VKPR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.vertigo-devops.com/vkpr-teste:$(date +%s)  
    - name: Image list
      run: docker image ls              
      
    - name: Run Commands with a Secret
      env:
            SECRET_VALUE_LOGIN: ${{ secrets.NEXUS_LOGIN_KEY }}
            SECRET_VALUE_PASSWORD: ${{ secrets.NEXUS_PASSWORD_KEY }}
      run: |
          echo "Hello "
          echo "\\   ^__^"
          echo " \\  (oo)\\_______"
          echo "     (__)\\    )\\/\\"
          echo "      ||----w |"
          echo "      ||     ||"                   
          echo "This is a secret login value: $SECRET_VALUE_LOGIN"
          echo "This is a secret password value: $SECRET_VALUE_PASSWORD"
          
    - name: Login to Nexus
      uses: docker/login-action@v2
      with:
          registry: docker.vertigo-devops.com
          username: ${{ secrets.NEXUS_LOGIN_KEY }}
          password: ${{ secrets.NEXUS_PASSWORD_KEY }}
            echo "Login repositorie nexus"
          
    - name: Push image Nexus          
            echo "Push repositorie nexus"
          
